CREATE DATABASE TechStore;

USE TechStore;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    detalhes TEXT,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
